name: AI Knowledge Document Assistant Backend- CI/CD

on:
    push:
        branches:
            - master

permissions:
    contents: read
    id-token: write

env:
    AWS_REGION: ap-south-2
    LAMBDA_FUNCTION_NAME: ai-knowledge-document-assistant

jobs:
    build-and-deploy:
        name: Build and Deploy Backend
        runs-on: ubuntu-latest
        environment: production

        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Scan for secrets
              uses: gitleaks/gitleaks-action@v2

            - name: Setup Java 21
              uses: actions/setup-java@v5
              with:
                  distribution: temurin
                  java-version: "21"

            - name: Grant execute permission
              run: chmod +x gradlew

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v5

            - name: Build application
              run: ./gradlew clean bootJar

            - name: Prepare Lambda package
              run: |
                  mkdir -p build/lambda
                  cp build/libs/*.jar build/lambda/application.jar

            - name: Debug GitHub OIDC claims
              uses: github/actions-oidc-debugger@main
              with:
                  audience: sts.amazonaws.com

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v5
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Deploy Lambda
              uses: aws-actions/aws-lambda-deploy@v1.1.0
              with:
                  function-name: ${{ env.LAMBDA_FUNCTION_NAME }}
                  code-artifacts-dir: build/lambda
                  handler: org.aiknowledge.aws.StreamLambdaHandler::handleRequest
                  runtime: java21
                  publish: true
